repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        always_run: true
        pass_filenames: false
