[project]
name = "videodev"
version = "0.1.0"
description = "Video processing with manim, pandas, etc"
dependencies = [
    "pandas",
    "manim",
    "pre-commit",
    "black",
    "mypy",
    "isort"
]
requires-python = ">=3.10"